### ISSUE TITLE
HTU21D Sensor Support

### ISSUE THREAD

**Issue by jptrsn** [jptrsn/ESP32-mqtt-room#20]
Add support for reading from and reporting temperature and humidity values from HTU21D i2c sensors to MQTT topics.

This should be modular and optional so that the basic functionality of the module is unchanged.

**Comment by mikewebb70** [comment]
I think this a brilliant idea....along with the led support as well and yep, modular.  Thanks for your efforts.

**Comment by jptrsn** [comment]
Basic support for HTU21D temperature/humidity sensor is now supported. Settings file includes `htuSensorTopic` option, to allow config to specify what MQTT topic pattern to use for reporting sensor values.

**Comment by jptrsn** [comment]
Released in `v0.0.7`
