### ISSUE TITLE
WS2812 Support

### ISSUE THREAD

**Issue by jptrsn** [jptrsn/ESP32-mqtt-room#22]
Add support for WS2812 LED to be used as status indicator rather than built-in LED.

Implement use of LEDs as mqtt light component.

Visually indicate state of switch if using GPIO cap sense input (requires completion of #21 )

**Comment by jptrsn** [comment]
I am no longer using this project, so I will not implement.

**Comment by anarchking** [comment]
Have you moved on to something better?

**Comment by jptrsn** [comment]
I actually was not using the data from the room presence sensors themselves, so I moved away from this project and am using ESPHome for various purposes.
