### ISSUE TITLE
Update presence channel when beacons are no longer actively seen.

### ISSUE THREAD

**Issue by akkord64** [jptrsn/ESP32-mqtt-room#24]
Would be good to update the presence topic when the last seen device(s) are no longer seen.

**Comment by jptrsn** [comment]
The logic to determine away state is handled by the `mqtt_room` component in Home Assistant. These sensors do not determine when a device is not seen, as they do not retain any information about what devices it has seen beyond the point of reporting them to Home Assistant.

You can modify the timeout settings for each sensor individually in the sensor configuration in Home Assistant. (See the documentation for more information)[https://www.home-assistant.io/components/mqtt_room/]. This ensures consistency across all sensors, as it is managed centrally.
