### ISSUE TITLE
Xiaomi Blé température support 

### ISSUE THREAD

**Issue by thundergreen** [jptrsn/ESP32-mqtt-room#3]
Would be nice having also support for Xiaomi ble Temperature sensors like in openmqttgateway

https://github.com/1technophile/OpenMQTTGateway/

**Comment by jptrsn** [comment]
I plan on implementing support for the Mi Flora plant sensor, as I have those on hand. I don't have any other Xiaomi sensors I can test with, however.

**Comment by jptrsn** [comment]
@thundergreen Do you have an example of what sensor you would like to see implemented?
