### ISSUE TITLE
humidity and temperature sensor library suggestion

### ISSUE THREAD

**Issue by Novocaine85** [jptrsn/ESP32-mqtt-room#37]
Hey,
This is not really an issue related to your project, but any advice is appreciated.
I'm using 3 esp32 flashed with your project around my house and they are working pretty good.

I have attached to those esp32 the HTU21D temperature and humidity sensor as well, but the library that i used ([this one](https://github.com/enjoyneering/HTU21D)) is messing up my sensors since when there is a crc error it sends 255 as result.

I don't know why i have those crc errors, generally are just in the umidity sensor, but not in the temperature. This happens in all the 3 esp32 devices.

Is there any other library that i can use?
Thanks

**Comment by jptrsn** [comment]
I'm not sure. I have seen those incorrect values come back from using this library as well. You may find it simpler to just filter them out, or you can try replacing the library with something else. I'm no longer actively using this project, so I don't plan on developing it any further.
