### ISSUE TITLE
How do I configure it in homeassistant?

### ISSUE THREAD

**Issue by 1043717432** [jptrsn/ESP32-mqtt-room#4]
Brush is written to esp8266, how do you configure yaml in homeassistant?

**Comment by jptrsn** [comment]
You'll need to ensure that you're using an ESP32, not an ESP8266. To configure in home assistant, check out the docs on [the Home Assistant page](https://www.home-assistant.io/components/sensor.mqtt_room/).

You can also ask in [the home assistant community thread](https://community.home-assistant.io/t/presence-detection-with-low-cost-ble-devices-and-raspberry-pi-zero-w/).
