### ISSUE TITLE
No wifi network connection

### ISSUE THREAD

**Issue by mrloggyst** [jptrsn/ESP32-mqtt-room#44]
create own "Settings_local.h" file change in "ESP32-mqtt-room.ino" to use them.
Build and upload.
After press reset  button on device serial port monitor show next:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:10124
load:0x40080400,len:5828
entry 0x400806a8
[E][esp32-hal-misc.c:218] initArduino(): Failed to initialize NVS! Error: 4368
Connecting to WiFi...
[E][WiFiGeneric.cpp:137] wifiLowLevelInit(): esp_wifi_init 4353
First contact!

Starting access point for configuration portal.
SSID: 'esp32-247d69'
[E][WiFiGeneric.cpp:137] wifiLowLevelInit(): esp_wifi_init 4353
[E][WiFiAP.cpp:97] softAP(): enable AP first!
0.0.0.0

No AP created. No wifi connection established for home wifi network.

**Comment by DereIBims** [comment]
Try an add the following Code to the `connectToWifi` Function after the `WiFi.setHostname()` :
`while(WiFi.status()!=WL_CONNECTED){
		yield();
	}`

Then it will connect to the WiFi but it doesn't find any Beacon

**Comment by jptrsn** [comment]
@philipkunes I have just published a new release to address the issue of finding no beacons. However, I am not able to reproduce your issue with wifi, so you will need to keep any changes you've made to your local version to get it working.
