### ISSUE TITLE
allowedListCheck by UUID and not Mac Add

### ISSUE THREAD

**Issue by soloam** [jptrsn/ESP32-mqtt-room#49]
**Is your feature request related to a problem? Please describe.**
The allowed List Check is checking the mac add, this is not useful for apps like the Home Assistant Companion on android, where we set the UUID, it would be better to check by UUID

**Describe the solution you'd like**
Same logic but for the UUID

**Describe alternatives you've considered**
Not a lot, the alternative is by Mac Add, but that exists

**Additional context**
Nothing to add

**Comment by nashant** [comment]
This would be fantastic
