### ISSUE TITLE
ESP32-wroom-32 not responding after 5-10 min

### ISSUE THREAD

**Issue by kirelam** [jptrsn/ESP32-mqtt-room#53]
**Describe the bug**
ESP32-wroom-32 not responding after 5-10 min, resulting in not sending the scanned iBeacons

**Configuration**
//Replace with your Wifi SSID; example: #define ssid "MyWifi"
#define ssid "HUIS"

//Replace with your Wifi password; example: #define password "12345678"
#define password "not the real PW"

//Replace with a human-friendly host name. Must not contain spaces or special characters and be unique on your network
#define hostname "BLE_Tracker_1"

//Replace with your MQTT Broker address; example: #define mqttHost IPAddress(192, 168, 1, 195)
#define mqttHost IPAddress(192, 168, 1, 50)

//Replace with your MQTT Broker port; example: #define mqttPort 1883
#define mqttPort 1883

//Replace with your MQTT Broker user; example: #define mqttUser "homeassistant"
#define mqttUser "HUIS"

//Replace with your MQTT Broker password; example: #define mqttPassword "12345678"
#define mqttPassword "not the real PW"

//Replace with the room name where the node will be placed; example: #define room "living-room"
#define room "ROOM_1"

//Specify the LED pin. For most dev boards, this is GPIO2
#define LED_BUILTIN 2

// Logic level for turning the led on. Most boards use active low, meaning LED_ON should be set to 0
#define LED_ON 0

//Define the base topic for room detection. Usually "room_presence"
#define channel "room_presence"

//Define the topic for publishing availability
#define availabilityTopic "presence_nodes/" room

//Define the topic for publishing JSON attributes
#define telemetryTopic "presence_nodes/" hostname "/tele"

// Define bluetooth scan parameters
#define scanInterval 5 // Define the interval in seconds between scans
#define singleScanTime 5 // Define the duration of a single scan in seconds
#define activeScan true // Active scan uses more power, but get results faster
#define bleScanInterval 0x80 // Used to determine antenna sharing between Bluetooth and WiFi. Do not modify unless you are confident you know what you're doing
#define bleScanWindow 0x10 // Used to determine antenna sharing between Bluetooth and WiFi. Do not modify unless you are confident you know what you're doing

// Maximum distance (in meters) to report. Devices that are calculated to be further than this distance in meters will not be reported
#define maxDistance 5

// MQTT topic for sensor values from HTU21D temperature and humidity sensor
//#define htuSensorTopic "presence_nodes/" hostname "/sensor"

//List of allowed MAC Addresses for MQTT Publish. All others will be ignored.
//Feature is disabled by default.
#define allowedListCheck false
String allowedList[] = {"11223344aabb", "11223344aabb"};
uint32_t allowedListNumberOfItems = 2;

**Logs**
Not possible

**Hardware Details**
ESP32-wroom-32

**To Reproduce**
after a power pull it instantly works again, and than after 5-10 minutes gets unresponsive

**Expected behavior**
Stable sending of signal

**Screenshots**
not possible

**Additional context**

**Comment by jptrsn** [comment]
This is likely a network or environment issue. Are you able to connect to the USB port on the device and read the logs from the serial port? If your device is attempting to use the same host name on your network, or client name on your mqtt server, this can cause intermittent connection issues. The serial terminal output will indicate when a disconnect happens, and indicate the reason why. In theory, the codebase should auto-reconnect if it drops the connection to wifi.

Please try to monitor the output and paste the output you see when the disconnection occurs. You can also use formatting in your reply by starting the line with a > character.
